### ISSUE TITLE
how to aur that creates 2 packages?

### ISSUE THREAD

**Issue by brunnels** [binhex/scripts#2]
I'm trying to modify your binhex-intellij to utilize the ultimate edition but I'm running into a problem because the intellij-idea-ultimate-edition aur creates intellij-idea-ultimate-edition and intellij-idea-ultimate-edition-jre packages.  I've tried all 3 combinations in the install.sh and end up with only the jre package installed each time.  I've also tried changing the order to no avail.

```
aur_packages="intellij-idea-ultimate-edition"
aur_packages="intellij-idea-ultimate-edition intellij-idea-ultimate-edition-jre"
aur_packages="intellij-idea-ultimate-edition-jre"
```

Also, for the aur.sh script it is a **lot** faster to not compress the package after building since you're just going to install it and then delete it after.

`sed -i -e "s~PKGEXT='.pkg.tar.xz'~PKGEXT='.pkg.tar'~g" /etc/makepkg.conf`

**Comment by binhex** [comment]
you are probably falling foul of the apacman introduction of regex matching on package name, this can cause problems if the package names are similar, try this:-

```
aur_packages="^intellij-idea-ultimate-edition-jre$ ^intellij-idea-ultimate-edition$"
```
