### ISSUE TITLE
HOST_OS changed in unraid 6.9.0

### ISSUE THREAD

**Issue by brunnels** [binhex/scripts#5]
https://github.com/binhex/scripts/blob/2d9a635c36ebd4a682f117ebb2d8f33763deb168/shell/arch/docker/init.sh#L21

I was wondering why permissions were not getting set and it looks like, at least on my server, that HOST_OS is now `Unraid`.

`export` from a running container:
```
declare -x HOME="/root"
declare -x HOSTNAME="a276e4ca1e55"
declare -x HOST_OS="Unraid"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PGID="100"
declare -x PUID="99"
declare -x PWD="/"
declare -x SHLVL="1"
declare -x TZ="America/Chicago"
declare -x UMASK="000"
```

**Comment by binhex** [comment]
thanks for this, ive put in a fix, however i should point out that this has nothing to do with setting permissions, it simply echo's out that the host is running unraid, nothing more.

**Comment by brunnels** [comment]
Yeah, I just noticed that I wasn't seeing the expected echo while I was debugging :) 

Thanks you for your all your contributions!  I prefer arch and use your base image for a lot of my personal containers, many not unraid.
